# Generated by Django 5.2.7 on 2025-11-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_insights_conversation_key_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='chat.message'),
        ),
    ]
