# Generated by Django 5.2.7 on 2025-11-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_branch_name_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
